---
data_store:
  address: "127.0.0.1:3306"
  username: $admin_username
  password: $admin_password
  schema: data_store_profiler

index_count: 3000
seed_count: 100
growth_factor: 2
buffer_size: 100000
iterations: 1000000
start_time: 2016-01-01 00:00:00
time_step: 10ms
...
