---
server:
  interface: "$local_interface:20500"
  addresses: ["$global_address:20500", "$local_interface:20500"]

service_locator:
  address: $service_locator_address
  username: registry_service
  password: $admin_password
...
