---
server:
  interface: "$local_interface:20900"
  addresses: ["$global_address:20900", "$local_interface:20900"]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema

service_locator:
  address: $service_locator_address
  username: uid_service
  password: $admin_password
...
