---
server:
  interface: "$local_interface:20000"
  addresses: ["$global_address:20000", "$local_interface:20000"]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema
...
